_wandb:
    value:
        cli_version: 0.23.0
        e:
            yknw42a6sgbjf92bih1d30dzcjrr36sl:
                codePath: streamlit_app.py
                codePathLocal: streamlit_app.py
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "4281044992"
                email: alfandary1@mail.tau.ac.il
                executable: /usr/local/bin/python3.11
                git:
                    commit: 0244a28a3148c59e0174c5ba76f65b0534d6c588
                    remote: https://github.com/tomer1806/DS-FinalProject-TomerandYAli
                host: codespaces-52f071
                memory:
                    total: "8330579968"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.31
                program: streamlit_app.py
                python: CPython 3.11.13
                root: /workspaces/DS-FinalProject-TomerandYAli
                startedAt: "2025-11-24T13:40:22.563733Z"
                writerId: yknw42a6sgbjf92bih1d30dzcjrr36sl
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
lr:
    value: 0.1
n_estimators:
    value: 100
